type StyleIds = {
  "mdc-elevation-overlay": string|undefined
  "mdc-dialog__scrim": string|undefined
  "mdc-dialog": string|undefined
  "mdc-dialog__surface": string|undefined
  "mdc-dialog__title": string|undefined
  "mdc-dialog__content": string|undefined
  "mdc-dialog--scrollable": string|undefined
  "mdc-dialog__actions": string|undefined
  "mdc-dialog__container": string|undefined
  "mdc-list": string|undefined
  "mdc-dialog--stacked": string|undefined
  "mdc-dialog__button": string|undefined
  "mdc-dialog--closing": string|undefined
  "mdc-dialog--opening": string|undefined
  "mdc-dialog--open": string|undefined
  "mdc-dialog-scroll-lock": string|undefined
  "mdc-line-ripple": string|undefined
  "mdc-line-ripple--active": string|undefined
  "mdc-line-ripple--deactivating": string|undefined
  "mdc-list-item": string|undefined
  "mdc-list-item__secondary-text": string|undefined
  "mdc-list-item__graphic": string|undefined
  "mdc-list-item__meta": string|undefined
  "mdc-list-group__subheader": string|undefined
  "mdc-list-item--disabled": string|undefined
  "mdc-list-item__text": string|undefined
  "mdc-list-item__primary-text": string|undefined
  "mdc-list-item--activated": string|undefined
  "mdc-list-item--selected": string|undefined
  "mdc-list--dense": string|undefined
  "mdc-list--icon-list": string|undefined
  "mdc-list--avatar-list": string|undefined
  "mdc-list--thumbnail-list": string|undefined
  "mdc-list--image-list": string|undefined
  "mdc-list--video-list": string|undefined
  "material-icons": string|undefined
  "mdc-list--two-line": string|undefined
  "mdc-list-divider": string|undefined
  "mdc-list-divider--padded": string|undefined
  "mdc-list-divider--inset": string|undefined
  "mdc-list-divider--inset-leading": string|undefined
  "mdc-list-divider--inset-trailing": string|undefined
  "mdc-list-divider--padding": string|undefined
  "mdc-list-divider--inset-padding": string|undefined
  "mdc-list-group": string|undefined
  "mdc-list-item__ripple": string|undefined
  "mdc-ripple-upgraded": string|undefined
  "mdc-ripple-upgraded--unbounded": string|undefined
  "mdc-ripple-upgraded--foreground-activation": string|undefined
  "mdc-ripple-upgraded--foreground-deactivation": string|undefined
  "mdc-ripple-upgraded--background-focused": string|undefined
  "mdc-theme--primary": string|undefined
  "mdc-theme--secondary": string|undefined
  "mdc-theme--background": string|undefined
  "mdc-theme--surface": string|undefined
  "mdc-theme--error": string|undefined
  "mdc-theme--on-primary": string|undefined
  "mdc-theme--on-secondary": string|undefined
  "mdc-theme--on-surface": string|undefined
  "mdc-theme--on-error": string|undefined
  "mdc-theme--text-primary-on-background": string|undefined
  "mdc-theme--text-secondary-on-background": string|undefined
  "mdc-theme--text-hint-on-background": string|undefined
  "mdc-theme--text-disabled-on-background": string|undefined
  "mdc-theme--text-icon-on-background": string|undefined
  "mdc-theme--text-primary-on-light": string|undefined
  "mdc-theme--text-secondary-on-light": string|undefined
  "mdc-theme--text-hint-on-light": string|undefined
  "mdc-theme--text-disabled-on-light": string|undefined
  "mdc-theme--text-icon-on-light": string|undefined
  "mdc-theme--text-primary-on-dark": string|undefined
  "mdc-theme--text-secondary-on-dark": string|undefined
  "mdc-theme--text-hint-on-dark": string|undefined
  "mdc-theme--text-disabled-on-dark": string|undefined
  "mdc-theme--text-icon-on-dark": string|undefined
  "mdc-theme--primary-bg": string|undefined
  "mdc-theme--secondary-bg": string|undefined
  "mdc-touch-target-wrapper": string|undefined
  "mdc-button": string|undefined
  "mdc-button__ripple": string|undefined
  "mdc-button__icon": string|undefined
  "mdc-button__touch": string|undefined
  "mdc-button__label": string|undefined
  "mdc-button--outlined": string|undefined
  "mdc-button--unelevated": string|undefined
  "mdc-button--raised": string|undefined
  "mdc-button--touch": string|undefined
  "mdc-elevation--z0": string|undefined
  "mdc-elevation--z1": string|undefined
  "mdc-elevation--z2": string|undefined
  "mdc-elevation--z3": string|undefined
  "mdc-elevation--z4": string|undefined
  "mdc-elevation--z5": string|undefined
  "mdc-elevation--z6": string|undefined
  "mdc-elevation--z7": string|undefined
  "mdc-elevation--z8": string|undefined
  "mdc-elevation--z9": string|undefined
  "mdc-elevation--z10": string|undefined
  "mdc-elevation--z11": string|undefined
  "mdc-elevation--z12": string|undefined
  "mdc-elevation--z13": string|undefined
  "mdc-elevation--z14": string|undefined
  "mdc-elevation--z15": string|undefined
  "mdc-elevation--z16": string|undefined
  "mdc-elevation--z17": string|undefined
  "mdc-elevation--z18": string|undefined
  "mdc-elevation--z19": string|undefined
  "mdc-elevation--z20": string|undefined
  "mdc-elevation--z21": string|undefined
  "mdc-elevation--z22": string|undefined
  "mdc-elevation--z23": string|undefined
  "mdc-elevation--z24": string|undefined
  "mdc-elevation-transition": string|undefined
  "mdc-menu": string|undefined
  "mdc-menu__selection-group": string|undefined
  "mdc-menu__selection-group-icon": string|undefined
  "mdc-menu-item--selected": string|undefined
  "mdc-switch__thumb-underlay": string|undefined
  "mdc-switch__native-control": string|undefined
  "mdc-switch": string|undefined
  "mdc-switch--checked": string|undefined
  "mdc-switch__track": string|undefined
  "mdc-switch__thumb": string|undefined
  "mdc-switch--disabled": string|undefined
  "mdc-card": string|undefined
  "mdc-card--outlined": string|undefined
  "mdc-card__media": string|undefined
  "mdc-card__media--square": string|undefined
  "mdc-card__media--16-9": string|undefined
  "mdc-card__media-content": string|undefined
  "mdc-card__primary-action": string|undefined
  "mdc-card__actions": string|undefined
  "mdc-card__actions--full-bleed": string|undefined
  "mdc-card__action-icons": string|undefined
  "mdc-card__action-buttons": string|undefined
  "mdc-card__action": string|undefined
  "mdc-card__action--button": string|undefined
  "mdc-card__action--icon": string|undefined
  "mdc-fab": string|undefined
  "mdc-fab--extended": string|undefined
  "mdc-fab__ripple": string|undefined
  "mdc-fab__icon": string|undefined
  "mdc-fab--mini": string|undefined
  "mdc-fab__label": string|undefined
  "mdc-fab--touch": string|undefined
  "mdc-fab__touch": string|undefined
  "mdc-fab--exited": string|undefined
  "mdc-menu-surface": string|undefined
  "mdc-menu-surface--open": string|undefined
  "mdc-menu-surface--animating-open": string|undefined
  "mdc-menu-surface--animating-closed": string|undefined
  "mdc-menu-surface--anchor": string|undefined
  "mdc-menu-surface--fixed": string|undefined
  "mdc-menu-surface--fullwidth": string|undefined
  "mdc-tab": string|undefined
  "mdc-tab__text-label": string|undefined
  "mdc-tab__icon": string|undefined
  "mdc-tab--min-width": string|undefined
  "mdc-tab__content": string|undefined
  "mdc-tab--stacked": string|undefined
  "mdc-tab--active": string|undefined
  "mdc-tab__ripple": string|undefined
  "mdc-typography": string|undefined
  "mdc-typography--headline1": string|undefined
  "mdc-typography--headline2": string|undefined
  "mdc-typography--headline3": string|undefined
  "mdc-typography--headline4": string|undefined
  "mdc-typography--headline5": string|undefined
  "mdc-typography--headline6": string|undefined
  "mdc-typography--subtitle1": string|undefined
  "mdc-typography--subtitle2": string|undefined
  "mdc-typography--body1": string|undefined
  "mdc-typography--body2": string|undefined
  "mdc-typography--caption": string|undefined
  "mdc-typography--button": string|undefined
  "mdc-typography--overline": string|undefined
  "2": string|undefined
  "8": string|undefined
  "mdc-checkbox": string|undefined
  "mdc-checkbox__native-control": string|undefined
  "mdc-checkbox__background": string|undefined
  "mdc-checkbox--selected": string|undefined
  "mdc-checkbox__ripple": string|undefined
  "mdc-checkbox--anim-unchecked-indeterminate": string|undefined
  "mdc-checkbox--anim-unchecked-checked": string|undefined
  "mdc-checkbox--anim-indeterminate-unchecked": string|undefined
  "mdc-checkbox--anim-checked-unchecked": string|undefined
  "mdc-checkbox__checkmark": string|undefined
  "mdc-checkbox__mixedmark": string|undefined
  "mdc-checkbox--disabled": string|undefined
  "mdc-checkbox--upgraded": string|undefined
  "mdc-checkbox__checkmark-path": string|undefined
  "mdc-checkbox--anim-checked-indeterminate": string|undefined
  "mdc-checkbox--anim-indeterminate-checked": string|undefined
  "mdc-checkbox--touch": string|undefined
  "mdc-notched-outline": string|undefined
  "mdc-notched-outline__trailing": string|undefined
  "mdc-notched-outline__notch": string|undefined
  "mdc-notched-outline__leading": string|undefined
  "mdc-floating-label": string|undefined
  "mdc-floating-label--float-above": string|undefined
  "mdc-notched-outline--upgraded": string|undefined
  "mdc-notched-outline--notched": string|undefined
  "mdc-notched-outline--no-label": string|undefined
  "mdc-tab-bar": string|undefined
  "mdc-chip-trailing-action__touch": string|undefined
  "mdc-chip-trailing-action": string|undefined
  "mdc-chip-trailing-action__icon": string|undefined
  "mdc-chip-trailing-action__ripple": string|undefined
  "mdc-chip__icon--leading": string|undefined
  "mdc-chip__icon--trailing": string|undefined
  "mdc-chip__icon": string|undefined
  "mdc-chip__icon--leading-hidden": string|undefined
  "mdc-chip": string|undefined
  "mdc-chip__ripple": string|undefined
  "mdc-chip--selected": string|undefined
  "mdc-chip__checkmark": string|undefined
  "mdc-chip__touch": string|undefined
  "mdc-chip--exit": string|undefined
  "mdc-chip__overflow": string|undefined
  "mdc-chip__text": string|undefined
  "mdc-chip__checkmark-path": string|undefined
  "mdc-chip__primary-action": string|undefined
  "mdc-chip-set--choice": string|undefined
  "mdc-chip__checkmark-svg": string|undefined
  "mdc-chip-set--filter": string|undefined
  "mdc-chip-set": string|undefined
  "mdc-chip--touch": string|undefined
  "mdc-chip-set--input": string|undefined
  "mdc-floating-label--required": string|undefined
  "mdc-floating-label--shake": string|undefined
  "mdc-radio": string|undefined
  "mdc-radio__native-control": string|undefined
  "mdc-radio__background": string|undefined
  "mdc-radio__outer-circle": string|undefined
  "mdc-radio__inner-circle": string|undefined
  "mdc-radio--touch": string|undefined
  "mdc-radio--disabled": string|undefined
  "mdc-radio__ripple": string|undefined
  "mdc-tab-indicator": string|undefined
  "mdc-tab-indicator__content--underline": string|undefined
  "mdc-tab-indicator__content--icon": string|undefined
  "mdc-tab-indicator__content": string|undefined
  "mdc-tab-indicator--active": string|undefined
  "mdc-tab-indicator--no-transition": string|undefined
  "mdc-tab-indicator--fade": string|undefined
  "mdc-icon-button": string|undefined
  "mdc-icon-button__icon": string|undefined
  "mdc-icon-button__icon--on": string|undefined
  "mdc-icon-button--on": string|undefined
  "mdc-ripple-surface": string|undefined
  "mdc-ripple-surface--primary": string|undefined
  "mdc-ripple-surface--accent": string|undefined
  "mdc-tab-scroller": string|undefined
  "mdc-tab-scroller--animating": string|undefined
  "mdc-tab-scroller__scroll-content": string|undefined
  "mdc-tab-scroller__test": string|undefined
  "mdc-tab-scroller__scroll-area": string|undefined
  "mdc-tab-scroller__scroll-area--scroll": string|undefined
  "mdc-tab-scroller--align-start": string|undefined
  "mdc-tab-scroller--align-end": string|undefined
  "mdc-tab-scroller--align-center": string|undefined
}
declare const styleIds: StyleIds
export default styleIds